Project_TaskManagementSystem_WebApplication/TaskManagementSystem_WebApplication/Controllers/UserPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagementSystem_WebApplication.Repository;
using TaskManagementSystem_WebApplication.Models;
using System.IO;
using TaskManagementSystem_WebApplication.Utilities;

namespace TaskManagementSystem_WebApplication.Controllers
{
    [Authorize]
    public class UserPageController : Controller
    {
        private readonly UserRepository _userRepository;
        private readonly AdminRepository _adminRepository;
        public UserPageController()
        {
            _userRepository = new UserRepository();
            _adminRepository = new AdminRepository();
        }
        /// <summary>
        /// GET: UserPage
        /// </summary>
        /// <returns></returns>
        public ActionResult UserDashBoard()
        {
            try
            {
                string profilePhoto = Session["ProfilePhoto"] as string;
                ViewBag.ProfilePhoto = profilePhoto;
                var userId = Session["UserID"] != null ? (int)Session["UserID"] : 0;
                var taskList = _userRepository.GetTaskDetailsByID(userId);
                return View(taskList);
            }
            catch (Exception ex)
            {
                ErrorLog.LogError(ex);
                TempData["ErrorMessage"] = "An error occurred while loading the page. Please try again later.";
                return View("ErrorView");
            }
        }
        // GET: UserPage/Details/5
        //public ActionResult TaskDetails(int id)
        //{
        //    var task = _userRepository.GetTaskDetailsByID(id).FirstOrDefault();
        //    return View(task);
        //}
        public ActionResult TaskDeatils(int id)
        {
            try
            {
                var task = _userRepository.GetTaskDetailsByTask(id).FirstOrDefault();
                TempData["TaskID"] = id;
                return View(task);
            }
            catch (Exception ex)
            {
                ErrorLog.LogError(ex);
                TempData["ErrorMessage"] = "An error occurred while loading the page. Please try again later.";
                return View("ErrorView");
            }
        }
        /// <summary>
        /// GET: UserPage/Edit
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>lient
        public ActionResult UpdateTaskProgress(int id)
        {
            try
            {
                TaskProgress taskProgress = _userRepository.GetTaskDetailsUpdate(id).FirstOrDefault();
                TempData["TaskID"] = id;
                return View(taskProgress);
            }
            catch (Exception ex)
            {
                ErrorLog.LogError(ex);
                TempData["ErrorMessage"] = "An error occurred while loading the page. Please try again later.";
                return View("ErrorView");
            }
        }
        /// <summary>
        /// UpdateTaskProgress
        /// </summary>
        /// <param name="taskProgress"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateTaskProgress(TaskProgress taskProgress)
        {
            try
            {
                taskProgress.TaskID = (int)TempData["TaskID"];
                if (taskProgress.TaskProgressFile != null && taskProgress.TaskProgressFile.ContentLength > 0)
                {
                    using (var binaryReader = new BinaryReader(taskProgress.TaskProgressFile.InputStream))
                    {
                        byte[] imageBytes = binaryReader.ReadBytes(taskProgress.TaskProgressFile.ContentLength);
                        taskProgress.TaskFile = Convert.ToBase64String(imageBytes);
                    }
                }
                _userRepository.UpdateTaskDetailsByUser(taskProgress);
                return RedirectToAction("UserDashBoard");
            }
            catch (Exception ex)
            {
                ErrorLog.LogError(ex);
                TempData["ErrorMessage"] = "An error occurred while updating the task progress. Please try again later.";
                return View("ErrorView");
            }
        }
        /// <summary>
        /// DeleteTaskbyUser/// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteTaskbyUser(int id)
        {
            try
            {
                var task = _userRepository.GetTaskDetailsByTask(id).FirstOrDefault();
                if (task == null)
                {
                    return RedirectToAction("AdminDashboard");
                }
                return View(task);
            }
            catch (Exception ex)
            {
                ErrorLog.LogError(ex);
                TempData["ErrorMessage"] = "An error occurred while loading the page. Please try again later.";
                return View("ErrorView");
            }
        }
        /// <summary>
        /// DeleteTaskbyUser        /// </summary>
        /// <param name="id"></param>
        /// <param name="collection"></param>
        /// <returns></returns>

        [HttpPost]
        public ActionResult DeleteTaskbyUser(int id, FormCollection collection)
        {
            try
            {
                _userRepository.DeleteTask(id);
                return RedirectToAction("AdminDashBoard", "AdminPage");
            }
            catch (Exception ex)
            {
                ErrorLog.LogError(ex);
                TempData["ErrorMessage"] = "An error occurred while task deletion. Please try again later.";
                return View("ErrorView");
            }
        }
        /// <summary>
        /// create task
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateTaskForUser()
        {
            try
            {
                var model = new Tasks();
                var allUsers = _adminRepository.GetAllUsers();
                var allProjects = _adminRepository.GetAllProjects();
                var allClients = _adminRepository.GetAllClients();
                var userSelectList = allUsers.Select(details => new
                {
                    UserID = details.UserID,
                    Username = details.Username,
                    EmailAddress = details.EmailAddress
                }).ToList();

                var projectSelectList = allProjects.Select(project => new
                {
                    ProjectID = project.ProjectID,
                    ProjectName = project.ProjectName
                }).ToList();

                var clientSelectList = allClients.Select(client => new
                {
                    ClientID = client.ClientID,
                    ClientName = client.ClientName
                }).ToList();
                ViewBag.Users = userSelectList;
                ViewBag.Projects = projectSelectList;
                ViewBag.Clients = clientSelectList;

                return View(model);
            }
            catch (Exception ex)
            {
                ErrorLog.LogError(ex);
                TempData["ErrorMessage"] = "An error occurred while loading the page. Please try again later.";
                return View("ErrorView");
            }
        }
        /// <summary>
        /// POST: AdminPage/Create Task
        /// </summary>
        /// <param name="tasks"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateTaskForUser(Tasks tasks)
        {
            try
            {
                var userId = Session["UserID"] != null ? (int)Session["UserID"] : 0;
                tasks.CreatedBy = userId;
                _adminRepository.CreateTask(tasks);
                return RedirectToAction("AdminDashboard");
            }
            catch (Exception ex)
            {
                ErrorLog.LogError(ex);
                TempData["ErrorMessage"] = "An error occurred while task creation. Please try again later.";
                return View("ErrorView");
            }
        }
        /// <summary>
        /// get report by user id
        /// </summary>
        /// <returns></returns>
        public ActionResult GetReportByUSER()
        {
            try
            {
                var userId = Session["UserID"] != null ? (int)Session["UserID"] : 0;

                var reportby = _userRepository.GetReportByUserID(userId);
                return View(reportby);
            }
            catch (Exception ex)
            {
                ErrorLog.LogError(ex);
                TempData["ErrorMessage"] = "An error occurred while loading the page. Please try again later.";
                return View("ErrorView");
            }
        }
        /// <summary>
        /// get report by task id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GetReportByID(int id)
        {
            try
            {
                var reportby = _userRepository.GetReportByID(id);
                return View(reportby);
            }
            catch (Exception ex)
            {
                ErrorLog.LogError(ex);
                TempData["ErrorMessage"] = "An error occurred while loading report. Please try again later.";
                return View("ErrorView");
            }
        }
    }
}

Project_TaskManagementSystem_WebApplication/TaskManagementSystem_WebApplication/Views/Shared/AdminPage_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AdminPage_Layout</title>

    <link href="~/Content/CustomCSS/AdminPage.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/CustomCSS/signUpForm.css" rel="stylesheet" />
</head>
<body>
    <div>

        <div class="navbarContainer">
            <ul class="navbar_row">
                <!-- Left Side: Logo and Site Name -->
                <li class="navbar_left navbar_list">
                    <a class="active" href="@Url.Action("MainDashboard", "HomePage")">
                        <img src="~/Content/Images/tasklogo2.png" alt="TaskHive Logo" id="taskhiveLogo">
                        <span class="site-name">TaskHive</span>
                    </a>
                </li>

                <!-- Right Side: Links (About Us, Contact Us, Sign In, Sign Up) -->
                <div class="navbar_right_container">
                @*<li class="navbar_right navbar_list"><a href="@Url.Action("SignUpPage_demo","HomePage")" method="post"><span class="glyphicon glyphicon-user"></span> Add new user</a></li>*@
                <div class="navbar">
                    <div class="profile">
                        @if (!string.IsNullOrEmpty(ViewBag.ProfilePhoto))
                        {
                            <!-- Profile Picture (clickable) -->
                            <img src="data:image/png;base64,@ViewBag.ProfilePhoto" alt="Profile Photo" id="profilePic" style="max-width: 100px; max-height: 100px;" />
                        }
                        else
                        {
                            <!-- No profile picture available (also clickable) -->
                            <div id="noPhoto" style="cursor: pointer; color: gray; font-size: 14px;">Admin</div>
                        }

                        <!-- Dropdown menu (initially hidden) -->
                        <div class="menu" id="dropdownMenu">
                            <a href="@Url.Action("UpdateUserAcoountPage","HomePage")">Update Profile</a>
                            <a href="@Url.Action("SignOut","AdminPage")">Signout</a>
                        </div>
                    </div>
                </div>
        </div>
        </ul>
    </div>
    <div>
        <div class="pagecontainer">
            <div class="sidebar" id="sidebar">
                <p id="sidebardDshboard"><a href="@Url.Action("AdminDashBoard","AdminPage")"> Dashboard</a></p>
                <p><a href="@Url.Action("GetAllTasks","AdminPage")"> Tasks</a></p>

                <p> <a href="@Url.Action("GetComments","AdminPage")">Inquiries</a></p>
                <p> <a href="@Url.Action("GetAllClients","AdminPage")">Clients</a></p>
                <p> <a href="@Url.Action("GetAllReports","AdminPage")">Report</a></p>
                <p> <a href="@Url.Action("GetProjects","AdminPage")">Projects</a></p>
                @*<p> <a href="@Url.Action("AdminSignUpPage","HomePage")">Add new admin</a></p>*@
                <p> <a href="@Url.Action("PasswordReset","AdminPage")">Reset password</a></p>
                <h4>Welcome  @ViewBag.FirstName</h4> <!-- Display the username -->


            </div>

            @RenderBody()
        </div>
        <hr />
        <footer class="footer">
            <div class="footerContainer">
                <div class="footerColumn">
                    <h4>Task hive</h4>
                    <div class="socialIcons">
                        <a href="#" target="_blank"><img src="~/Content/Images/fb3.png" alt="Facebook"></a>
                        <a href="#" target="_blank"><img src="~/Content/Images/instagramLogo.png" alt="Twitter"></a>
                        <a href="#" target="_blank"><img src="~/Content/Images/LinkedinLogo.png" alt="Instagram"></a>
                    </div>
                </div>

                <div class="footerColumn">
                    <h4>Links</h4>
                    <ul>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms of Use</a></li>
                    </ul>
                </div>

                <div class="footerColumn">
                    <h4>Contact Us</h4>
                    <p>Email: contact@taskhive.com</p>
                    <p>Phone: +123 456 7890</p>
                    <p>Address: 123 Main St, Ernakulam, India</p>
                </div>
            </div>

            <!-- Copyright Row -->
            <div class="footerCopyright">
                <p>&copy; 2024 Taskhive. All rights reserved.</p>
            </div>
        </footer>

    </div>


    </div>
   
    <script src="~/Scripts/CustomJS/signupdemo.js"></script>
    <script src="~/Scripts/CustomJS/TaskForm.js"></script>
    <script src="~/Scripts/CustomJS/Common.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

Project_TaskManagementSystem_WebApplication/TaskManagementSystem_WebApplication/Views/Shared/ErrorView.cshtml
@{
    ViewBag.Title = "ErrorView";
    Layout = "~/Views/Shared/HomePage_Layout.cshtml";
}

<h2>Error</h2>

@if (TempData["ErrorMessage"] != null)
{
    <div class="errorMessage" id="ErrorData">
        @TempData["ErrorMessage"]
    </div>
}

<p>Something went wrong. Please try again later or contact support if the issue persists.</p>

<a href="@Url.Action("MainDashboard", "HomePage")">Return to Home Page</a>

Project_TaskManagementSystem_WebApplication/TaskManagementSystem_WebApplication/Views/Shared/HomePage_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HomePage_Layout</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.5/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate.unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    @Styles.Render("~/Content/CustomCSS/HomePage.css")
    <link href="~/Content/CustomCSS/signUpForm.css" rel="stylesheet" />
    <link href="~/Content/CustomCSS/HomePage.css" rel="stylesheet" />
    <link href="~/Content/CustomCSS/Signin.css" rel="stylesheet" />
    @RenderSection("HeadScripts", required: false)
</head>
<body>
    <div>
        <div class="navbarContainer">
            <ul class="navbar_row">
                <!-- Left Side: Logo and Site Name -->
                <li class="navbar_left navbar_list">
                    <a class="siteLogo" href="@Url.Action("MainDashboard", "HomePage")">
                        <img src="~/Content/Images/tasklogo2.png" alt="TaskHive Logo" id="taskhiveLogo">
                        <span class="site-name">TaskHive</span>
                    </a>
                </li>

                <!-- Right Side: Links (About Us, Contact Us, Sign In, Sign Up) -->
                <div class="navbar_toggle" onclick="toggleNavbar()">☰</div>
                <div class="navbar_right_container">
                <li class="navbar_right navbar_list"><a href="@Url.Action("AboutUs", "HomePage")">About us</a></li>
                <li class="navbar_right navbar_list"><a href="@Url.Action("ContactPage", "HomePage")">Contact us</a></li>
                <li class="navbar_right navbar_list"><a href="@Url.Action("SignUpPage_demo", "HomePage")"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
                <li class="navbar_right navbar_list"><a href="@Url.Action("SignInPage", "HomePage")"><span class="glyphicon glyphicon-log-in"></span> Sign in</a></li>
        </div>
    </div>
    </ul>
    </div>

    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer class="footer">
            <div class="footerContainer">
                <div class="footerColumn">
                    <h3>Task hive</h3>
                    <h4>Follow us</h4>
                    <div class="socialIcons">
                        <a href="#" target="_blank"><img src="~/Content/Images/fb3.png" alt="Facebook"></a>
                        <a href="#" target="_blank"><img src="~/Content/Images/instagramLogo.png" alt="Twitter"></a>
                        <a href="#" target="_blank"><img src="~/Content/Images/LinkedinLogo.png" alt="Instagram"></a>
                    </div>
                </div>

                <div class="footerColumn">
                    <h4>Links</h4>
                    <ul>
                        <li><a href="@Url.Action("AboutUs", "HomePage")">About us</a></li>
                        <li><a href="@Url.Action("ContactPage", "HomePage")">Contact us</a></li>
                        <li><a href="@Url.Action("SignInPage", "HomePage")" ">Sign in</a></li>
                        <li><a href="@Url.Action("SignUpPage", "HomePage")">SignUp</a></li>
                    </ul>
                </div>

                <div class="footerColumn">
                    <h4>Contact Us</h4>
                    <p>Email: contact@taskhive.com</p>
                    <p>Phone: +123 456 7890</p>
                    <p>Address: 123 Main St, Ernakulam, India</p>
                </div>
            </div>

            <!-- Copyright Row -->
            <div class="footerCopyright">
                <p>&copy; 2024 Taskhive. All rights reserved.</p>
            </div>
        </footer>
    </div>
    @RenderSection("scripts", required: false)


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.5/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate.unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script type="text/javascript"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/Scripts/CustomJS/signIn.js"></script>
    <script src="~/Scripts/CustomJS/homePage.js"></script>
    <script src="~/Scripts/CustomJS/Message.js"></script>

</body>
</html>

Project_TaskManagementSystem_WebApplication/TaskManagementSystem_WebApplication/Views/Shared/UserPage_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AdminPage_Layout</title>
    <link href="~/Content/CustomCSS/UserPage.css" rel="stylesheet" />

   
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <div class="navbarContainer">
            <ul class="navbar_row">
                <!-- Left Side: Logo and Site Name -->
                <li class="navbar_left navbar_list">
                    <a class="active" href="@Url.Action("MainDashboard", "HomePage")">
                        <img src="~/Content/Images/tasklogo2.png" alt="TaskHive Logo" id="taskhiveLogo">
                        <span class="site-name">TaskHive</span>
                    </a>
                </li>

                <!-- Right Side: Links (About Us, Contact Us, Sign In, Sign Up) -->
                <div class="navbar_right_container">

                <li class="navbar_right navbar_list"><a href="@Url.Action("GetReportByUser","UserPage")"><span class="glyphicon glyphicon-user"></span> Reports</a></li>
                <div class="profile">
                    @if (!string.IsNullOrEmpty(ViewBag.ProfilePhoto))
                    {
                        <!-- Profile Picture (clickable) -->
                        <img src="data:image/png;base64,@ViewBag.ProfilePhoto" alt="Profile Photo" id="profilePic" style="max-width: 100px; max-height: 100px;" />
                    }
                    else
                    {
                        <!-- No profile picture available (also clickable) -->
                        <div id="noPhoto" style="cursor: pointer; color: gray; font-size: 14px;">Admin</div>
                    }

                    <!-- Dropdown menu (initially hidden) -->
                <div class="menu" id="dropdownMenu">
                  
                    <a href="@Url.Action("UpdateUserAcoountPage","HomePage")">Update Profile</a>
                    <a href="@Url.Action("PasswordReset","AdminPage")">Reset password</a>
                    <a href="@Url.Action("SignOut","AdminPage")">Signout</a>
                </div>
                </div>

                <div>
            </ul>
        </div>
        <div>
            <div class="pagecontainer">

                @RenderBody()
            </div>
            <hr />
            <footer class="footer">
                <div class="footerContainer">
                    <div class="footerColumn">
                        <h4>Task hive</h4>
                        <div class="socialIcons">
                            <a href="#" target="_blank"><img src="~/Content/Images/fb3.png" alt="Facebook"></a>
                            <a href="#" target="_blank"><img src="~/Content/Images/instagramLogo.png" alt="Twitter"></a>
                            <a href="#" target="_blank"><img src="~/Content/Images/LinkedinLogo.png" alt="Instagram"></a>
                        </div>
                    </div>

                    <div class="footerColumn">
                        <h4>Links</h4>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Services</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Terms of Use</a></li>
                        </ul>
                    </div>

                    <div class="footerColumn">
                        <h4>Contact Us</h4>
                        <p>Email: contact@taskhive.com</p>
                        <p>Phone: +123 456 7890</p>
                        <p>Address: 123 Main St, Ernakulam, India</p>
                    </div>
                </div>

                <!-- Copyright Row -->
                <div class="footerCopyright">
                    <p>&copy; 2024 Taskhive. All rights reserved.</p>
                </div>
            </footer>

        </div>

    </div>
    <script src="~/Scripts/CustomJS/TaskForm.js"></script>
    <script src="~/Scripts/CustomJS/Common.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
   
</body>
</html>

Project_TaskManagementSystem_WebApplication/TaskManagementSystem_WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/CustomCSS/HomePage.css" rel="stylesheet" />
    <link href="~/Content/CustomCSS/signUpForm.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.14.0/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://code.jquery.com/ui/1.14.0/jquery-ui.js"></script>
    
</head>
<body>
    <div class="navbarContainer">
        <ul class="navbar_row">
            <!-- Left Side: Logo and Site Name -->
            <li class="navbar_left navbar_list">
                <a class="siteLogo" href="@Url.Action("MainDashboard", "HomePage")">
                    <img src="~/Content/Images/tasklogo2.png" alt="TaskHive Logo" id="taskhiveLogo">
                    <span class="site-name">TaskHive</span>
                </a>
            </li>

            <!-- Right Side: Links (About Us, Contact Us, Sign In, Sign Up) -->
            <div class="navbar_right_container">
            <li class="navbar_right navbar_list"><a href="@Url.Action("AboutUs", "HomePage")">About us</a></li>
            <li class="navbar_right navbar_list"><a href="@Url.Action("ContactPage", "HomePage")">Contact us</a></li>
            <li class="navbar_right navbar_list"><a href="@Url.Action("SignUpPage_demo", "HomePage")"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
            <li class="navbar_right navbar_list"><a href="@Url.Action("SignInPage", "HomePage")"><span class="glyphicon glyphicon-log-in"></span> Sign in</a></li>
        </ul>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>
    <footer class="footer">
        <div class="footerContainer">
            <div class="footerColumn">
                <h3>Task hive</h3>
                <h4>Follow us</h4>
                <div class="socialIcons">
                    <a href="#" target="_blank"><img src="~/Content/Images/fb3.png" alt="Facebook"></a>
                    <a href="#" target="_blank"><img src="~/Content/Images/instagramLogo.png" alt="Twitter"></a>
                    <a href="#" target="_blank"><img src="~/Content/Images/LinkedinLogo.png" alt="Instagram"></a>
                </div>
            </div>

            <div class="footerColumn">
                <h4>Links</h4>
                <ul>
                    <li><a href="@Url.Action("AboutUs", "HomePage")">About us</a></li>
                    <li><a href="@Url.Action("ContactPage", "HomePage")">Contact us</a></li>
                    <li><a href="@Url.Action("SignInPage", "HomePage")" ">Sign in</a></li>
                    <li><a href="@Url.Action("SignUpPage", "HomePage")">SignUp</a></li>
                </ul>
            </div>

            <div class="footerColumn">
                <h4>Contact Us</h4>
                <p>Email: contact@taskhive.com</p>
                <p>Phone: +123 456 7890</p>
                <p>Address: 123 Main St, Ernakulam, India</p>
            </div>
        </div>

        <!-- Copyright Row -->
        <div class="footerCopyright">
            <p>&copy; 2024 Taskhive. All rights reserved.</p>
        </div>
    </footer>
 
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>